### ISSUE TITLE
Water bottles are deleted when filling a cauldron

### ISSUE THREAD

**Issue by saltyseadoggo** [CursedFlames/StackablePotions#4]
When a player right clicks on a cauldron whilst holding a stack of more than one water bottle, all of the water bottles in the stack are deleted to yield one glass bottle. One would expect the glass bottle to be sent to an available space or dropped on the ground if there isn't one, and the stack of water bottles to be decremented by only one.

**Comment by CursedFlames** [comment]
Yeah I'll look into this one now
